spring:
  application:
    name: spring-sse
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: 'true'
  main:
    allow-bean-definition-overriding: 'true'
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: 'false'